# Generated by Django 3.2.5 on 2023-02-14 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventoryApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reciperequirement',
            name='unit',
            field=models.CharField(choices=[('tsp', 'tsp'), ('tbsp', 'tbsp'), ('oz', 'oz'), ('lbs', 'lbs'), ('each', 'each')], default='each', max_length=200),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='unit',
            field=models.CharField(choices=[('tsp', 'tsp'), ('tbsp', 'tbsp'), ('oz', 'oz'), ('lbs', 'lbs'), ('each', 'each')], max_length=10),
        ),
    ]
