# Generated by Django 3.2.5 on 2023-02-14 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventoryApp', '0002_auto_20230214_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='unit',
            field=models.CharField(choices=[('tsp', 'tsp'), ('tbsp', 'tbsp'), ('oz', 'oz'), ('lbs', 'lbs')], default='lbs', max_length=200),
        ),
        migrations.AlterField(
            model_name='reciperequirement',
            name='unit',
            field=models.CharField(choices=[('tsp', 'tsp'), ('tbsp', 'tbsp'), ('oz', 'oz'), ('lbs', 'lbs')], default='lbs', max_length=200),
        ),
    ]
