# Generated by Django 3.2.5 on 2023-02-14 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventoryApp', '0003_auto_20230214_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='unit',
            field=models.CharField(choices=[('tsp', 'Teaspoon'), ('tbsp', 'Tablespoon'), ('fl-oz', 'Fluid Ounce'), ('cup', 'Cup'), ('pint', 'Pint'), ('quart', 'Quart'), ('gallon', 'Gallon'), ('oz', 'Ounce'), ('lb', 'Pound')], default='lb', max_length=20),
        ),
        migrations.AlterField(
            model_name='reciperequirement',
            name='unit',
            field=models.CharField(choices=[('tsp', 'Teaspoon'), ('tbsp', 'Tablespoon'), ('fl-oz', 'Fluid Ounce'), ('cup', 'Cup'), ('pint', 'Pint'), ('quart', 'Quart'), ('gallon', 'Gallon'), ('oz', 'Ounce'), ('lb', 'Pound')], default='lb', max_length=20),
        ),
    ]
